:zap: template for model, controller, tests
it-projects-llc/bobtemplates.odoo pull request #4
Opened 2019-09-27 11:33 UTC by fedoranvar

2019-09-27 12:42 UTC, KolushovAlexandr requested changes
Add empty lines at the end of files where it's not done yet.

2019-09-27 12:42 UTC, KolushovAlexandr commented on bobtemplates/itpp/odoo/wizard/wizards/+wizard.name_underscored+.xml.bob
> -                <footer>
Restore group and footer is a good idea, I did not know it was already done.

2019-09-27 12:42 UTC, KolushovAlexandr commented on bobtemplates/itpp/odoo/wizard/wizards/+wizard.name_underscored+.xml.bob
> -    <record model="ir.actions.act_window" id="{{{ wizard.name_underscored }}}_act_window">
and this one too

2019-09-30 07:36 UTC, fedoranvar commented
> Add empty lines at the end of files where it's not done yet.

Haven't found any file that doesn't have an empty line in EOF

2019-09-30 08:36 UTC, KolushovAlexandr requested changes
* Properly update readme file. 
* When it asks for category it provides 'pos' as an example and then types it into the manifest as 'pos' not as "Point of Sale"
* smhw got this "https://apps.odoo.com/apps/modules/{VERSION}/bob_technical_name/"
* ```__pycache__``` dir appeared in modules repository
* no empty line at the end of changelog and index.rst files
* there is no a closing bracket at the last line of index.rst file
* icon file is broken
* if I typed version as '12' it pastes 12 everywhere, maybe make handler for those cases?
* 
```
mrbob bobtemplates.itpp.odoo:model
Traceback (most recent call last):
  File "/usr/local/bin/mrbob", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/mrbob/cli.py", line 155, in main
    defaults=defaults)
  File "/usr/local/lib/python3.5/dist-packages/mrbob/configurator.py", line 172, in __init__
    self.post_render = [resolve_dotted_func(f) for f in self.templateconfig.get('post_render', '').split()]
  File "/usr/local/lib/python3.5/dist-packages/mrbob/configurator.py", line 172, in <listcomp>
    self.post_render = [resolve_dotted_func(f) for f in self.templateconfig.get('post_render', '').split()]
  File "/usr/local/lib/python3.5/dist-packages/mrbob/configurator.py", line 45, in resolve_dotted_func
    module = import_module(module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'bobtemplates.odoo'
```
Instructions unclear got a duck stuck in a toaster

2019-09-30 08:36 UTC, KolushovAlexandr commented on setup.py
> +    description="mr.bob templates for Odoo projects (IT-Projects Edition",
```suggestion
    description="mr.bob templates for Odoo projects (IT-Projects Edition)",
```

2019-09-30 08:36 UTC, KolushovAlexandr commented on bobtemplates/itpp/odoo/view/.mrbob.ini
> +post_render = bobtemplates.itpp.odoo.hooks:post_render_view
```suggestion
post_render = bobtemplates.itpp.odoo.hooks:post_render_view

```

2019-09-30 08:36 UTC, KolushovAlexandr commented on bobtemplates/itpp/odoo/test/static/src/js/test_+test.name_underscored+.js.bob
> +
```suggestion
```

2019-09-30 08:36 UTC, KolushovAlexandr commented on bobtemplates/itpp/odoo/test/.mrbob.ini
> +post_render = bobtemplates.itpp.odoo.hooks:post_render_test
```suggestion
post_render = bobtemplates.itpp.odoo.hooks:post_render_test

```

2019-09-30 08:36 UTC, KolushovAlexandr commented on bobtemplates/itpp/odoo/controller/controllers/+controller.name_underscored+.py.bob
> +# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).
```suggestion
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).

```

2019-09-30 08:36 UTC, KolushovAlexandr commented on README.rst
> +  * ``wizard`` :
add description here

2019-09-30 08:36 UTC, KolushovAlexandr commented on README.rst
> +* Set copyright variables in ``.mrbob.ini`` in ``/path/to/config``:
There is no any link to available variables, what should i write there?

2019-09-30 08:36 UTC, KolushovAlexandr commented on README.rst
> +      [variables]
there was a notice about it somewhere above, and here it is again. But still, there is no proper example of available variables. Not sure that putting a version here is a good idea

2019-09-30 08:36 UTC, KolushovAlexandr commented on README.rst
> -* mr.bob readthedocs: https://mrbob.readthedocs.io/en/latest/index.html
why this one was deleted?

2019-09-30 08:36 UTC, KolushovAlexandr commented on bobtemplates/itpp/copyright/.mrbob.ini
> +pre_render = bobtemplates.itpp.hooks:pre_render_copyright
```suggestion
pre_render = bobtemplates.itpp.hooks:pre_render_copyright

```

2019-10-02 11:11 UTC, merged